---
apiVersion: v1
kind: Service
metadata:
  name: bms-app-db-service
  labels:
    app: bms-app-db-service
spec:
  type:NodePort
  ports:
   - port: 3306
     targetPort: 3306
     protocal: TCP
  selector:
    app:bms-app-db-pod