---
apiVersion: apps/v1
kind: ReplicSet
metadata: 
  name: javawebapprs
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata: 
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080